### ISSUE TITLE
Demo 1- Kết quả tìm kiếm - Map - search địa điểm

### ISSUE THREAD

**Issue by Minhmicviet** [reway/bds-web#11]
- search theo địa điểm chưa có bán kính để lọc, đang hiển thị toàn bộ kết quả.
VD: search theo đỉa điểm đại học thuỷ lợi, hiển thị ra toàn bộ HN
![screen shot 2016-05-18 at 1 38 02 pm](https://cloud.githubusercontent.com/assets/19279515/15349679/da727eb8-1cfe-11e6-8dc1-d977591874d5.png)

**Comment by hungdqht** [comment]
fixed, de ban kinh mac dinh 2km
