### ISSUE TITLE
Demo1 - Ket qua tim kiem Map - Bo sung thong tin hien thi tren design

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#14]
Hi Minh,
Minh xem giúp anh các nội dung khoanh đỏ trên trang Map: 
- đã hiển thị đúng so với nội dung yêu cầu ?
- nội dung tiếng Anh có cần để không ? Nếu để thì thay bằng thông tin gì ?

![screen shot 2016-06-07 at 12 34 50 am](https://cloud.githubusercontent.com/assets/6210499/15831516/324d8666-2c48-11e6-9dfb-85fd31aef5fb.png)

![screen shot 2016-06-07 at 12 37 48 am](https://cloud.githubusercontent.com/assets/6210499/15831559/680fff72-2c48-11e6-9a83-89dd4909559b.png)

**Comment by vietthanh30** [comment]
@Minhmicviet

**Comment by Minhmicviet** [comment]
- Ô thứ nhất : 
Loại nhà, giá, diện tích, số phòng (số tầng), hướng, địa chỉ ( bỏ địa chính map đang show)
![screen shot 2016-05-23 at 10 48 56 am](https://cloud.githubusercontent.com/assets/19279515/15918760/95a4544a-2e34-11e6-8ca7-f2aacc54d2df.png)

- Ô thứ 2 : dự án tiêu biểu 
- Ô thứ 3 : Loại nhà, giá, diện tích, số phòng (số tầng), hướng, địa chỉ chi tiết
- Ô thứ 4: Nhà Cần bán gấp, Nhà chính chủ, nhà mới giảm giá
- Ô thứ 5 : Hiển thị địa chính đang search 
@vietthanh30
