### ISSUE TITLE
Demo1 - Ket qua tim kiem List - Bo sung thong tin hien thi tren design

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#15]
Hi Minh,
Một số nội dung hiển thị bằng tiếng Anh, Minh xem mục nào để, mục nào bỏ. Nếu để thì thay thế bằng thông tin gì?

![screen shot 2016-06-07 at 6 52 44 am](https://cloud.githubusercontent.com/assets/6210499/15841650/0f967d6e-2c7d-11e6-8e35-d588b67f7256.png)

![screen shot 2016-06-07 at 6 53 04 am](https://cloud.githubusercontent.com/assets/6210499/15841672/3130f170-2c7d-11e6-8002-fa8f9d9258e8.png)

**Comment by vietthanh30** [comment]
@Minhmicviet

**Comment by Minhmicviet** [comment]
Tính từ trên xuống dưới từ trái qua phải anh nhé 👍 
- Ô đỏ thứ nhất bỏ
- Ô đỏ thử 2 sau này sẽ điền các thông tin nổi bật : Nhà cần bán gấp, nhà mới giảm giá, nhà chính chủ ( khách phải mua để được gắn những thông tin này ) 
- Ô đỏ thứ 3: thay thê cho các dự án nổi bật, thu tiền quảng cáo
- Ô đỏ thứ 4 : địa điểm hoặc địa chính đang search vd: Hanoi > Cầu Giấy > Đường Xuân Thuỷ
@vietthanh30

**Comment by Minhmicviet** [comment]
- anh nhớ check cái file các thức thu tiền để biết các nút cần bán gấp, nhà mới giảm giá, nhà chính chủ ntn anh nhé 👍 
https://docs.google.com/spreadsheets/d/1PgGcczPPgT4ANN8CYjtzACCiSPV3idJI9Oyowj44uoM/edit#gid=1226785985
