### ISSUE TITLE
Trang chủ - Hiển thị ảnh sole giống Trulia

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#16]
Hiện tại anh đang để 2 BDS/1dòng trong xấu

![list-detail](https://cloud.githubusercontent.com/assets/6210499/16715007/b1bfc0e6-46fe-11e6-88c0-218258f196a8.jpg)

**Comment by vietthanh30** [comment]
@Minhmicviet
Hi Minh,
Trang chủ hiện tại chỉ hiển thị 2 BDS trên 1 dòng, do phần lớn diện tích sử dụng cho ô search. Phiên bản mới bọn anh đã sửa để hiển thị sole giống Trulia. Bản này sẽ deploy trong tuần này, sau khi design gửi bản sửa conflict giao diện.
![list-home](https://cloud.githubusercontent.com/assets/6210499/16715012/dfd7c410-46fe-11e6-95ab-749d0e072a85.jpg)

**Comment by vietthanh30** [comment]
@Minhmicviet
Anh thấy để 2 BDS trên 1 dòng ở trang home như hiện tại là hợp lý, sample của Minh show 7 BDS của trang detail. Em confirm xem mình làm giống trang home của Trulia hay trang Detail của Trulia

**Comment by Minhmicviet** [comment]
anh làm giôngs trulia là được, chắc do màn hình imac của em to nó hiển thị 7 cái, nó tự điều chỉnh hiển thị theo kích thước thiết bị. nhưng anh hiển thị sole cho đẹp.
