### ISSUE TITLE
Chi tiết BDS - Hiển thị bị mờ trên IMAC 21'

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#23]
9-khi click vào chi tiết anh, ko hiểu sao mờ quá anh ah, em dùng imac 21", laptop ko bị

**Comment by vietthanh30** [comment]
@Minhmicviet
Anh sử dụng Mac Pro. Ảnh hiển thị tốt. Issue này nếu chỉ xuất hiện đối với IMAC thì để sau mình quay lại kiểm tra và xử lý. Anh nghĩ ko phải do web.

![gui-yeu-cau](https://cloud.githubusercontent.com/assets/6210499/16715225/2c883e3e-4704-11e6-8c4a-d38feba150b0.jpg)

**Comment by Minhmicviet** [comment]
ok anh
