### ISSUE TITLE
Kết quả tìm kiếm Map - Phần hiển thị danh sách BDS: 2BDS/1 dòng

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#25]
11- trong hiển thị kết quả tìm kiếm, danh sách BĐS anh đang để 2BDS/1 dòng, anh xem hiển thị của trulia nhé

**Comment by vietthanh30** [comment]
@Minhmicviet
Minh mô tả kỹ hơn phần này xem mình cần phải làm gì

**Comment by Minhmicviet** [comment]
anh hiển thị như Trulia là được anh ạh

**Comment by hungdqht** [comment]
@Minhmicviet ,@vietthanh30 
trulia phần search hiển thị 2 ảnh trên dòng thôi mà nhỉ?

**Comment by Minhmicviet** [comment]
ok anh, em comment nhầm ở home page.
