### ISSUE TITLE
Demo1 - Ket qua tim kiem List - Title của BDS đang dùng adsID

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#3]

**Comment by vietthanh30** [comment]
Cần dùng tiêu đề BDS thay thế cho adsID
![screen shot 2016-05-18 at 8 25 57 am](https://cloud.githubusercontent.com/assets/6210499/15344608/4978713c-1cd2-11e6-8768-64b1f644cb8e.png)

**Comment by hungdqht** [comment]
truong title qua dai de dien vao day can thong nhat lai la chuan hoa the nao hoac cat ngan title cho phu hop
