### ISSUE TITLE
Trang chủ - Làm sáng hơn ảnh nền của phần search

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#34]

**Comment by vietthanh30** [comment]
@Minhmicviet: Ảnh nền đã sáng hơn. Minh kiểm tra xem cần sửa gì không.
Ảnh nền trang chủ mình lấy từ Trulia. Khi go live cần thay bằng ảnh khác. Minh biên tập giúp anh 3 ảnh. Kích thước  w x h : 1280 × 1338

**Comment by vietthanh30** [comment]
@Minhmicviet: Đã thay bằng ảnh Minh mới gửi. Em xem phần này có yêu cầu gì thêm ko ?

**Comment by Minhmicviet** [comment]
ok ròi anh. @vietthanh30
