### ISSUE TITLE
Font chữ WEB

### ISSUE THREAD

**Issue by Minhmicviet** [reway/bds-web#38]
Font chữ vẫn chưa chuẩn anh ạh, logo sao mờ vậy anh nhỉ @vietthanh30 @hungdqht

**Comment by vietthanh30** [comment]
@Minhmicviet : Em kiểm tra xem font đã được chưa. 
Logo em gửi anh màu trắng. Em mô tả kỹ hơn về issue này. Logo trên menu bị mờ ?

**Comment by Minhmicviet** [comment]
font ngon rồi anh. anh cho đậm chữ trên menu lên xem có đẹp hơn ko nhé, đang để nét mảnh
logo nếu làm nét hơn, kích thước lớn hơn anh có đưa được vào logo ko hay bắt buộc phải như kích thước anh đưa ?
@vietthanh30

**Comment by vietthanh30** [comment]
@Minhmicviet : font đậm vậy đc chưa Minh ?

**Comment by Minhmicviet** [comment]
được rồi anh ạh :D @vietthanh30  cái logo anh thay ảnh to chưa ?
