### ISSUE TITLE
Demo1 - Home page - Search

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#6]
Cập nhật mục search theo design mới bỏ mục "Đã bán"

**Comment by Minhmicviet** [comment]
- Thiếu bộ lọc " hướng" trên tap menu 
- search theo địa điểm theo tiêu chí gì vậy anh, em thấy hiện hết
- bộ lọc chưa chuẩn, anh sắp xếp ô search ở trên các bộ lọc như Trulia được ko, để như mình dùng chuột ko thuận.

**Comment by vietthanh30** [comment]
@Minhmicviet
- Bộ lọc hướng trên Tab Menu: Phần tìm kiếm nâng cao vào bộ lọc nâng cao đã có nội dung này. Cần trao đổi để thống nhất xem có nên đưa vào không, có tổng cộng 8 hướng rất khó để bố trí trên thanh tìm kiếm của trang chủ. Nội dung này anh đã note trong excel file là phải trao đổi lại. Phần này em trao đổi với Bình xem có nên làm ko và nếu làm thì bố trí thế nào cho hợp lý.
- Search theo địa điểm theo các tiêu chí:
   + Địa chính (Tỉnh, Huyện, Xã)
   + Địa điểm (Dự án, đường, tòa nhà, trường học, ...)
- Bộ lọc hiện tại tham khảo từ Realtor.com (đã note trong excel file). Phần này đã trao đổi rất kỹ với Bình từ đầu. Mục tiêu để như vậy để người dùng có thể dễ dàng biết được toàn bộ tiêu chí tìm kiếm.

**Comment by Minhmicviet** [comment]
trên iphone lệnh search trên web bi lỗi, Ipad vẫn ok @vietthanh30
