### ISSUE TITLE
Demo1 - Ket qua tim kiem List - Phân trang 

### ISSUE THREAD

**Issue by vietthanh30** [reway/bds-web#9]
Phần này làm chưa giống thiết kế

Hiện tại
![screen shot 2016-05-18 at 8 29 27 am](https://cloud.githubusercontent.com/assets/6210499/15344711/3a0294de-1cd3-11e6-9a8f-0beaa7acd05e.png)

Thiết kế
![screen shot 2016-05-18 at 8 34 33 am](https://cloud.githubusercontent.com/assets/6210499/15344729/60db57c6-1cd3-11e6-9831-cceaa2c0852b.png)

**Comment by hungdqht** [comment]
cai phan trang lam giong nhau thoi. design co list voi map khac nhau nen dang chon 1 cai de lam
